version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.6-management
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=airflow
            - RABBITMQ_DEFAULT_PASS=airflow
            - RABBITMQ_DEFAULT_VHOST=airflow

    webserver:
        build: .
        restart: always
        depends_on:
            - rabbitmq
        volumes:
            - ~/dags:/airflow/dags
        ports:
            - "8082:8080"
        command: webserver

    flower:
        build: .
        restart: always
        depends_on:
            - rabbitmq
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            # - LOAD_EX=n
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
        command: scheduler -n 5

    worker:
        build: .
        restart: always
        depends_on:
            - scheduler
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Celery
        command: worker
