version: '2'
services:
    postgres:
        build: postgres/
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    # mysql:
    #     build: mysql/
    #     environment:
    #         - MYSQL_USER=airflow
    #         - MYSQL_PASSWORD=airflow
    #         - MYSQL_DATABASE=airflow
    #         - MYSQL_ROOT_PASSWORD=airflow

    webserver:
        image: ld00000/docker-airflow:0.1.1
        restart: always
        depends_on:
            - postgres
        environment:
            # - LOAD_EX=n
            - INIT_DB=y
            - EXECUTOR=Local
        volumes:
            - ~/dags:/airflow/dags
        ports:
            - "8082:8080"
        command: webserver

    scheduler:
        image: ld00000/docker-airflow:0.1.1
        restart: always
        depends_on:
            - webserver
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Local
        command: scheduler -n 5
